### ISSUE TITLE
悬浮窗多个activity公用 出现死循环的问题

### ISSUE THREAD

**Issue by ShuaiShuai-Code** [limbowangqi/FloatWindow#1]
作者你好，使用你的库解决了我的问题，加入到项目之后多次切换，出现死循环，请问作者有没有解决办法，我切换一次，这个循环是两次，返回再次进去，循环四次，我来回切换四五次，这个循环就到了上百次，直接ANR了，求教，解决办法

 private class MyHandler(val weakReference: WeakReference<FloatWindowImpl>) :
        Handler(Looper.getMainLooper()) {
        override fun handleMessage(msg: Message) {
            super.handleMessage(msg)

            weakReference.get()?.run {
                val token = activity?.window?.decorView?.windowToken
                if (token == null) {
                    LogUtil.e("===>show"+"token=null")
                    handler.sendMessageDelayed(handler.obtainMessage(), 100)
                } else {
                    windowManager =
                        activity?.getSystemService(Context.WINDOW_SERVICE) as WindowManager?
                    LogUtil.e("===>show"+token+"activity="+activity?.javaClass)
                    windowParams.token = token
                    show()
                }
            }
        }
    }

**Comment by limbowangqi** [comment]
demo里面没有出现Anr的情况，不过会有内存泄漏的问题。
我新版本换了一种实现方式，这几天会更新上去。

**Comment by ShuaiShuai-Code** [comment]
我是用库的时候 ，这个不是绑定application生命周期吗，我打印的onActivityResumed这个方法，第一次执行一次，进入第二个activity，就执行两次，返回再次进入第二个app就执行四次，返回再次进去就执行了8次，16次 23次这样一直到ANR，是不是我只用方式不对 

class ActivityLifecycle(private val floatWindow: IFloatWindow) : Application.ActivityLifecycleCallbacks {


    override fun onActivityResumed(activity: Activity) {
        LogUtil.e("onActivityResumed")
        floatWindow.show(activity)
    }

    override fun onActivityPaused(activity: Activity) {
//        floatWindow.hide()
    }
