### ISSUE TITLE
拖动不跟手

### ISSUE THREAD

**Issue by General110** [limbowangqi/FloatWindow#6]
class MovingDraggable : BaseDraggable() {
//    private var downX = 0f
//    private var downY = 0f

    private var isMoving = false

    private var initialX = 0
    private var initialY = 0
    private var initialTouchX = 0f
    private var initialTouchY = 0f

    override fun onTouch(v: View?, event: MotionEvent?): Boolean {
        when (event?.action) {
            MotionEvent.ACTION_DOWN -> {
                initialX = floatBuilder.absoluteXY.first
                initialY = floatBuilder.absoluteXY.second
                initialTouchX = event.rawX
                initialTouchY = event.rawY
                isMoving = false
            }

            MotionEvent.ACTION_MOVE -> {
                if (!isMovingXY(initialTouchX, initialTouchY, event.rawX, event.rawY)) {
                    return false
                }
                isMoving = true
                updateLocation((initialX + (event.rawX - initialTouchX)).toInt(), (initialY + (event.rawY - initialTouchY)).toInt())
                return true
            }

            MotionEvent.ACTION_UP -> {
                return isMoving
            }
        }
        return v?.isClickable != true
    }
}  这样会好点

**Comment by wustwg** [comment]
> class MovingDraggable : BaseDraggable() { // private var downX = 0f // private var downY = 0f
> 
> ```
> private var isMoving = false
> 
> private var initialX = 0
> private var initialY = 0
> private var initialTouchX = 0f
> private var initialTouchY = 0f
> 
> override fun onTouch(v: View?, event: MotionEvent?): Boolean {
>     when (event?.action) {
>         MotionEvent.ACTION_DOWN -> {
>             initialX = floatBuilder.absoluteXY.first
>             initialY = floatBuilder.absoluteXY.second
>             initialTouchX = event.rawX
>             initialTouchY = event.rawY
>             isMoving = false
>         }
> 
>         MotionEvent.ACTION_MOVE -> {
>             if (!isMovingXY(initialTouchX, initialTouchY, event.rawX, event.rawY)) {
>                 return false
>             }
>             isMoving = true
>             updateLocation((initialX + (event.rawX - initialTouchX)).toInt(), (initialY + (event.rawY - initialTouchY)).toInt())
>             return true
>         }
> 
>         MotionEvent.ACTION_UP -> {
>             return isMoving
>         }
>     }
>     return v?.isClickable != true
> }
> ```
> 
> } 这样会好点

你这个测试可用。但是拖到边缘还会变形。我看了代码，它每次位置变化都要重新测量宽高。哎。。感觉很简单的一个功能，好几个明显的bug。。。
